/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    Charts: typeof import('./src/components/Charts.vue')['default']
    ClockBtn: typeof import('./src/components/ClockBtn.vue')['default']
    LikeNum: typeof import('./src/components/LikeNum.vue')['default']
    Member: typeof import('./src/components/Member.vue')['default']
    NutCalendarCard: typeof import('@nutui/nutui-taro')['CalendarCard']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    PhoneLogin: typeof import('./src/components/PhoneLogin.vue')['default']
    SelectPerson: typeof import('./src/components/SelectPerson.vue')['default']
  }
}
